import { Contact } from '../types/Contact';

export const contacts: Contact[] = [
  {
    name: 'Maksym Kuznetsov',
    image: 'maksym_kuznetsov.jfif',
    id: 'dev-0',
    telegramLink: 'https://t.me/MaxSchmide',
    github: 'https://github.com/MaxSchmide',
    email: 'kuznetsov.max.v@gmail.com',
    linkedIn: 'https://www.linkedin.com/in/maxschmide/',
    motto: "It's not a bug, it's a feature",
  },
  {
    name: 'Olha Sheliakina',
    image: 'olha_sheliakina.jfif',
    id: 'dev-1',
    telegramLink: 'https://t.me/olia_sheliakina',
    github: 'https://github.com/OlhaSheliakina',
    email: 'olha.sheliakina.mail@gmail.com',
    linkedIn: 'https://www.linkedin.com/in/olha-sheliakina-248497283',
    motto: "Code, Debug, Don't Cry (Much)",
  },
  {
    name: 'Nazar Baraban',
    image: 'nazar_baraban.jfif',
    id: 'dev-2',
    telegramLink: 'https://t.me/nazar_10_04',
    github: 'https://github.com/NazarBaraban',
    email: 'barabannazar44@gmail.com',
    linkedIn: 'https://www.linkedin.com/in/nazar-baraban-5661b5283/',
    motto: 'Programmers never make mistakes, we just have unexpected features',
  },
  {
    name: 'Ihor Hladkov',
    image: 'ihor_hladkov.jfif',
    id: 'dev-3',
    telegramLink: 'https://t.me/ihorhladkov',
    github: 'https://github.com/ihorhladkov',
    email: 'ihor.hladkov@gmail.com',
    linkedIn: 'https://www.linkedin.com/in/ihor-hladkov-b9b481283/',
    motto:
      'Once, I asked, "What is the meaning of life?" In response, I received, "Read the documentation."',
  },
  {
    name: 'Vlad Roznatovskyi',
    image: 'vlad_roznatovskyi.jfif',
    id: 'dev-4',
    telegramLink: 'https://t.me/perfectAcedia',
    github: 'https://github.com/perfectAcedia',
    email: 'vladyslav.roznatovskyi@gmail.com',
    linkedIn: 'https://www.linkedin.com/in/vladyslav-roznatovskyi-3b9491283/',
    motto: 'No desire, no hire',
  },
  {
    name: 'Olena Vats',
    image: 'olena_vats.jfif',
    id: 'dev-5',
    telegramLink: 'https://t.me/olenaOle1',
    github: 'https://github.com/olena-ole',
    email: 'olenavats.employment@gmail.com',
    linkedIn: 'https://www.linkedin.com/in/olena-vats-20ab131b8/',
    motto: 'It works on my machine',
  },
];
